---
blank_issues_enabled: false
contact_links:
  - name: Discussions
    url: https://github.com/tenthirtyam/setup-task/discussions/new/choose
    about: The starting point for questions, assistance, and discussions about this project.
  - name: Task Documentation
    url: https://taskfile.dev
    about: Need help with Task in general? Check out the Task documentation.
  - name: Sponsor this Project
    url: https://github.com/sponsors/tenthirtyam
    about: Support this project by sponsoring it on GitHub.
  - name: Buy Me a Coffee
    url: https://buymeacoffee.com/tenthirtyam
    about: Support this project by buying me a coffee.
